image: node:latest

before_script:
  - apt-get update -qq && apt-get install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy:
  stage: deploy
  image: ruby:latest
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=punto-chat --api-key=$HEROKU_API_KEY
